<?php $this->setLayout('phpico_layout') ?>

<?php $this->block('container-width-px') ?>
400
<?php $this->endblock('container-width-px') ?>

<?php $this->block('content') ?>

<div class="box">

    <h1>Welcome to <span class="font-primary">NixPHP</span>!</h1>
    <p>To begin developing, you may add your first route to <strong>/app/routes.php</strong>.</p>

    <hr />

    <?php $code = <<<CODE
    // File: app/routes.php
    
    use function NixPHP\\response;
    use function NixPHP\\route;
    
    &lt;?php
    
    route()->add('GET', '/', function() {
        return response('Hello World!');
    });
    CODE; ?>

    <h2>Example</h2>
    <div class="code">
        <pre><?= $code ?></pre>
    </div>

    <hr />

    <div class="footer">

        <a href="https://github.com/fkde/phpico/wiki" target="_blank">Documentation</a>
        <a href="https://github.com/fkde/phpico" target="_blank">Github</a>

    </div>

</div>

<?php $this->endblock('content') ?>
