<?php $this->setLayout('layout') ?>

<?php $this->block('container-width-px') ?>
400
<?php $this->endblock('container-width-px') ?>

<?php $this->block('content') ?>

<div class="box">

    <h1>Welcome to <span class="font-primary">PHPico</span>!</h1>
    <p>To begin developing, you may add your first route to <strong>/app/routes.php</strong>.</p>

    <hr />

    <h2>Example</h2>
    <div class="code">
        <pre>// File: app/routes.php<br/><br />&lt;?php<br /><br />route()->add('GET', '/', function() {<br />    return response('Hello World!');<br />});</pre>
    </div>

    <hr />

    <div class="footer">

        <a href="https://github.com/fkde/phpico/wiki" target="_blank">Documentation</a>
        <a href="https://github.com/fkde/phpico" target="_blank">Github</a>

    </div>

</div>

<?php $this->endblock('content') ?>
