<?php $this->setLayout('phpico_layout') ?>

<?php $this->block('content') ?>

<div class="box" style="line-height: 1.5rem">

    <h1 style="margin-bottom: 2rem">Error</h1>

    <div class="flex">
        <strong style="font-size: 10pt; width: 5rem;">Message:</strong> <span><?= $message ?></span>
    </div>
    <div class="flex">
        <strong style="font-size: 10pt; width: 5rem;">File:</strong> <span><?= $file ?></span>
    </div>

    <div class="flex">
        <strong style="font-size: 10pt; width: 5rem;">Line:</strong> <span><?= $line ?></span>
    </div>

    <hr />

    <h2 style="margin-bottom: 0;">Stacktrace:</h2>
    <pre><?= $trace ?></pre>

</div>

<?php $this->endblock('content') ?>

