site_name: NixPHP
site_description: A modern, minimalist PHP microframework
theme:
  name: material
  palette:
    - scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Routing: routing.md
  - Controllers: controllers.md
  - Response Handling: response_handling.md
  - Dependency Injection: dependency_injection.md
  - Events: events.md
  - Plugins: plugins.md
  - Error Handling: error_handling.md
  - File Downloads: file_downloads.md
  - Guard: guard.md
  - Using External Libraries: external_libraries.md
  - Best Practices: best_practices.md
  - Optional Plugins:
    - Views: views.md
    - Database: database.md
    - Session: sessions.md

repo_url: https://github.com/nixphp/framework
repo_name: nixphp/framework
docs_dir: pages/
